# Generated by Django 3.1 on 2021-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='Poster',
            field=models.URLField(blank=True),
        ),
    ]
