# Generated by Django 3.1 on 2021-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0002_auto_20210226_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='movies'),
        ),
    ]
