# Generated by Django 3.1 on 2021-02-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0003_auto_20210226_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S_Genre',
            new_name='Genre',
        ),
    ]
