# Generated by Django 3.1 on 2021-02-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0004_auto_20210226_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_review',
            old_name='movie',
            new_name='serie',
        ),
    ]
