# Generated by Django 3.1 on 2021-02-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0005_auto_20210226_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
