# Generated by Django 3.1 on 2021-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210226_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='movies'),
        ),
    ]
