# Generated by Django 3.1 on 2021-02-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_auto_20210226_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
