# Generated by Django 3.1 on 2021-02-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_auto_20210226_1711'),
        ('documentary', '0002_auto_20210226_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentary',
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.AlterField(
            model_name='documentary',
            name='Actors',
            field=models.ManyToManyField(blank=True, to='actor.Actor'),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='movies'),
        ),
    ]
